### PR TITLE
Logging fix and database promise feature

### PR DESCRIPTION
**Pull request by dankahle**
fixes: #48 
Sorry for putting these together, but fixes the bug and allows database promises and doesn't affect the way code runs now. I don't see any contrib.md on winston, and can't figure out how these winston-mongodb tests get wrapped into the rest. Something's missing as I don't even see asserts.

### CODE REVIEW

**Comment by indexzero** [comment]
I'd prefer not to take a dependency on q. Thoughts everyone else?

**Comment by indexzero** [comment]
At the very least if this was to be accepted it needs tests and documentation explaining the feature.

**Comment by dankahle** [comment]
I'm not trying to get this accepted, just using the PR to show the code is all. It was already made clear there was no interest in the database promise, the bug on the other hand could use fixing, albeit I couldn't figure out the tests and there was no explanation of how these tests integrated to the main winston ones. Couldn't see a dependency in winston on them... I'm confused then.

**Comment by dankahle** [comment]
btw if someone's feeling generous down the git line... I can't figure this out:
1) I put all my changes in one commit push and PR, so when the owner merges, there's one commit for the change. I assume that's how it's done.
2) I get stuck making more changes, but... I still want that one commit, so I rebase/squash my commits locally, then try to push up the single commit. 

The push is denied because the github wants me to merge first. If I force push, the PR gets destroyed and I have to enter a new one, losing the old comment stream. If I do the merge, I get the mess I have now which is the original commit, a new commit with the new and old changes, and an empty merge commit. 
How exactly is this done? Surely I need to rebase/squash, and all looks fine locally, but how am I to get it up to github without it dropping the PR and forcing the merge. I'm lost on that.

**Comment by jcrugzz** [comment]
@dankahle i wouldnt worry about squashing your commits during the PR process. I'd just worry about making changes based on feedback and what you find :). I'm also -1 on the Q depedendency as its used for something fairly simple. The queuing of logs seems reasonable, I'm guessing this is meant to be used to buffer logs in memory until the database connection is initialized?

**Comment by 39dotyt** [comment]
@indexzero there should be no dependencies on any promises libraries. Adding promises support may be helpful, but it should support legacy ES6 promises and all compatible libraries. I will do it the right way sooner.
@jcrugzz logs queuing was already implemented in library. What @dankahle wants is to add promises support so it will be possible to pass promise object to the library, which will be resolved with connected database object.
@dankahle thank you for your contribution. I see that promises support may be helpful and will add it sooner. But, it's really bad idea to add Q or any other promises library as direct dependency because their are huge and you are using it for very simple task. Watch for updates.

**Comment by jcrugzz** [comment]
@39dotyt gotcha, it just seemed like he did add some defer operation logic which seemed useful if a string is passed in for the database to handle the connection and auto-creation of the collection.

**Comment by 39dotyt** [comment]
@jcrugzz not exactly, he added defer operation to handle scenario when pre-connected db object passed or promise object passed without checking whether it is promise object or db connection object. What he wants to achieve is to add support of passing promise object which will be resolved in pre-connected db objects as options.db.

**Comment by 39dotyt** [comment]
@dankahle please check out version 1.1.0. It now supports promises or other compatible thenable objects and includes fix for mentioned issue.

**Comment by dankahle** [comment]
Looks great @39dotyt , much leaner (without Q). I'm unfamiliar with all the variations of promises, i.e. would they all have a then() function? I have no idea, but one could hope. I was leaning on Q to do that work for me, i.e. it's supposed to convert other promises to Q promises, maybe all it does is check for a then function .... yep, my bad on that, just checks for isObject an then() function. Thanks for that (the promise option and the bug fix)

**Comment by 39dotyt** [comment]
@dankahle all promises objects _should have_ then function. As I know, Q isn't fully compatible with ES6 Promises standard, just look at the declaration syntax: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise. But it's objects also have then function, so it will work fine. I have added bluebird as dev dependencies for promises test. Bluebird is A+ Promises implementation (with some extended API, which I prefer not to use) with unmatched performance https://github.com/petkaantonov/bluebird/tree/master/benchmark.

**Pull request closed without merging**
