### PR TITLE
bump mongodb driver to 5.9.1

### PR DESCRIPTION
**Pull request by ahmedissa**
Hi,

Dependency Changes:

* minimum Node.js 6.8.1 => 14.20.1 (it's required for mongodb 5.9 driver)
* mongedb 3.6.2 => 5.9.1
* mongoose 7.3.4 => 7.6.1 (it uses mongodb 5.9 driver)

Code Changes:
* poolsize deprecated. Changed poolsize to maxPoolSize ([ref](https://mongodb.github.io/node-mongodb-native/2.2/api/MongoClient.html#.connect)).
* autoreconnect deprecated. Default is true.
* ObjectID replaced with ObjectId

Any help or guidance are appreciated.

### CODE REVIEW

**Comment by DABH** [comment]
@curledUpSheep any idea why your CI setup did not run on this PR?

**Comment by DABH** [comment]
At a glance, this looks good to me, but I'll note that due to the changes in required node versions etc., we would need to ship this as a major release (which I'm fine with).

**Comment by curledUpSheep** [comment]
@DABH CI did not run on this PR because it has conflicts. Apparently this is a GitHub Actions limitation.
See also https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request:

> Workflows will not run on `pull_request` activity if the pull request has a merge conflict. The merge conflict must be resolved first.
> Conversely, workflows with the `pull_request_target` event will run even if the pull request has a merge conflict. Before using the `pull_request_target` trigger, you should be aware of the security risks. For more information, see [`pull_request_target`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target).

Because of the mentioned security risks, I don't think it's a good idea to switch to using `pull_request_target`.

Based on the documentation, it seems that CI should run on this PR once conflicts are resolved.

**Comment by ahmedissa** [comment]
@curledUpSheep  @DABH 

I just fixed the conflict and i hope the changes land soon. 
Thanks a lot for responding and happy new year!

**Comment by DABH** [comment]
Going to close this one in favor of #290 and doing a major version release

**Pull request closed without merging**
