### PR TITLE
Bump mongodb to 6.5.0

### PR DESCRIPTION
**Pull request by Bharat94389**
see #218 

Changes done:
- bump mongodb to 6.5.0
- updated mongo config

@DABH can you please have a look at this PR

### CODE REVIEW

**Comment by KoshelevS** [comment]
@DABH Is it possible to merge this PR?

**Comment by DABH** [comment]
I can merge this but need to think about versioning.  Since default options are changing, this feels like it should be a major version release of `winston-mongodb`.  Do you folks agree?

**Comment by yurijmikhalevich** [comment]
@DABH, I agree.

**Comment by KoshelevS** [comment]
Sure. No problem.

**Comment by DABH** [comment]
@Bharat94389 Any chance you can rebase this PR so I can merge it?  (Or any other volunteers?)

**Comment by Bharat94389** [comment]
@DABH updated the PR please have a look

**Comment by DABH** [comment]
@Bharat94389 Thanks for updating!  It looks like there's now a test failure that doesn't occur on master.  Perhaps you have to just do `npm install ip -g --save` on your branch?  Anyway, should be good to merge once we get the tests passing again... thanks again for helping get this done!

**Comment by Bharat94389** [comment]
@DABH tried installing ip globally but didn't work so added as a dev package, and ran all the testcases locally as well.

**Comment by DABH** [comment]
Whoops, don't know why I typed -g, sorry, muscle memory!  Looks like tests are passing now so I will merge.  Thank you again!

**Comment by DABH** [comment]
Hey @yurijmikhalevich could I please get write permissions for the NPM repo https://www.npmjs.com/package/winston-mongodb so I can push out this major release?  Thanks!  (I'm `dabh` on NPM)

**Comment by DABH** [comment]
@yurijmikhalevich sorry to pester, but gentle bump on the above - any help is appreciated :)

**Comment by yurijmikhalevich** [comment]
@DABH, done. Thank **you**! :)

**Pull request merged**
